DROP TABLE IF EXISTS class;
DROP TABLE IF EXISTS class_fts;
DROP TABLE IF EXISTS jar;

CREATE TABLE jar (
  id    INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  path  TEXT NOT NULL UNIQUE,
  name  TEXT NOT NULL
) STRICT;

CREATE TABLE class (
  id    INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  jar   TEXT NOT NULL,
  fqn   TEXT NOT NULL
) STRICT;

